spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.242.149:3306/seata_order?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 192.168.242.149:8848
  application:
    name: seata-order-service

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.xiao.springcloud.entity

seata:
  registry:
    # 配置seata的注册中心， 告诉seata client 怎么去访问seata server(TC)
    type: nacos
    nacos:
      server-addr: 192.168.242.149:8848  # seata server 所在的nacos服务地址
      application: seata-server    # seata server 的服务名seata-server ，如果没有修改可以不配
      username: nacos
      password: nacos
      group: SEATA_GROUP          # seata server 所在的组，默认就是SEATA_GROUP，没有改也可以不配
  # 配置seata的配置中心，可以读取关于seata client的一下配置
  config:
    type: nacos
    nacos:
      server-addr: 192.168.242.149:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP

server:
  port: 8071
