server:
  port: 8088
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.242.150:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      scg:
        fallback:
          mode: response
          response-body: "{code:4444,message:限流了}"

    gateway:
      routes:
        - id: order_route  # 路由的唯一标识，路由到order
          uri: lb://order-service  #需要转发的地址   lb: 使用nacos中的本地负载均衡策略  order-service服务名
          predicates:
            - Path=/order/**
#      globalcors:
#        cors-configurations:
#          '[/**]':  # 允许跨域访问的资源
#            allowedOrigins: "*" # 跨域允许的来源
#            allowedMethods:
#              - GET
#              - POST
management:
  endpoints:
    web:
      exposure:
        include: '*'